// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7aG7d6IK4wSp1k_FBaqQnBD1lVZt_oKg',
    appId: '1:53007256094:web:d556baf3585eefb6717c0f',
    messagingSenderId: '53007256094',
    projectId: 'zarvisgenix-68ceb',
    authDomain: 'zarvisgenix-68ceb.firebaseapp.com',
    storageBucket: 'zarvisgenix-68ceb.appspot.com',
    measurementId: 'G-JP30WB44BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Q2yCOERKwXAwAxURAraJ7Wq7G_sepSk',
    appId: '1:53007256094:android:affdf21880c7a4f7717c0f',
    messagingSenderId: '53007256094',
    projectId: 'zarvisgenix-68ceb',
    storageBucket: 'zarvisgenix-68ceb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpFE3zS5rCEDuaJQnQZUpiA8pKNDS3gzY',
    appId: '1:53007256094:ios:8ceeddaa0b65f527717c0f',
    messagingSenderId: '53007256094',
    projectId: 'zarvisgenix-68ceb',
    storageBucket: 'zarvisgenix-68ceb.appspot.com',
    iosBundleId: 'com.example.zarvisGenixAssignment',
  );
}
